package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/qqz14/zctl/util/pathx"
)

// GenEnumFile generates pkg/enums/{snake_name}.go for a single enum.
// Called by:
//   - Path B (manual): `zctl rpc enum --name=OrderStatus --values=pending,paid,shipped,done`
//   - Path A (auto):   GenEnumsFromProto() during gen-rpc
func GenEnumFile(projectDir, name string, values []string) error {
	enumValues := make([]protoEnumValue, 0, len(values))
	for number, value := range values {
		enumValues = append(enumValues, protoEnumValue{Name: value, Number: int64(number)})
	}
	return genEnumFile(projectDir, name, enumValues)
}

func genEnumFile(projectDir, name string, values []protoEnumValue) error {
	dir := filepath.Join(projectDir, "pkg", "enums")
	if err := pathx.MkdirIfNotExist(dir); err != nil {
		return err
	}

	filename := toSnake(name) + ".go"
	filePath := filepath.Join(dir, filename)

	content := buildEnumContent(name, values)
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return err
	}

	fmt.Printf("[zctl] Generated enum: pkg/enums/%s (%d values)\n", filename, len(values))
	return nil
}

// GenEnumsFromProto scans desc/ for proto enum definitions and generates
// corresponding Go enum helper files in pkg/enums/.
// Called automatically during `make gen-rpc` (after merge-proto, before protoc).
func GenEnumsFromProto(projectDir string) error {
	descDir := filepath.Join(projectDir, "desc")
	if _, err := os.Stat(descDir); os.IsNotExist(err) {
		return nil
	}

	var protoFiles []string
	filepath.Walk(descDir, func(path string, info os.FileInfo, err error) error {
		if err == nil && !info.IsDir() && strings.HasSuffix(path, ".proto") {
			protoFiles = append(protoFiles, path)
		}
		return nil
	})

	for _, f := range protoFiles {
		enums, err := parseProtoEnums(f)
		if err != nil {
			continue
		}
		for _, e := range enums {
			if err := genEnumFile(projectDir, e.Name, e.Values); err != nil {
				return err
			}
		}
	}
	return nil
}

// protoEnum represents a parsed proto enum definition.
type protoEnum struct {
	Name   string
	Values []protoEnumValue
}

type protoEnumValue struct {
	Name   string
	Number int64
}

// parseProtoEnums extracts enum definitions from a proto file.
// Parses: enum Xxx { VALUE_A = 0; VALUE_B = 1; ... }
func parseProtoEnums(filePath string) ([]protoEnum, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}

	var enums []protoEnum
	lines := strings.Split(string(data), "\n")
	enumValueRe := regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?\d+)\s*(?:\[[^\]]*\])?\s*;(?:\s*//.*)?$`)

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		// Match: enum EnumName {
		if strings.HasPrefix(trimmed, "enum ") && strings.Contains(trimmed, "{") {
			parts := strings.Fields(trimmed)
			if len(parts) < 2 {
				continue
			}
			enumName := parts[1]
			var values []protoEnumValue
			braceDepth := strings.Count(trimmed, "{") - strings.Count(trimmed, "}")

			// Read enum-level values only; nested option blocks are metadata.
			for i++; i < len(lines); i++ {
				line := strings.TrimSpace(lines[i])
				if braceDepth == 1 {
					match := enumValueRe.FindStringSubmatch(line)
					if len(match) == 3 {
						value := protoEnumValueToName(enumName, match[1])
						number, err := strconv.ParseInt(match[2], 10, 64)
						if value != "" && err == nil {
							values = append(values, protoEnumValue{Name: value, Number: number})
						}
					}
				}

				braceDepth += strings.Count(line, "{") - strings.Count(line, "}")
				if braceDepth <= 0 {
					break
				}
			}

			if len(values) > 0 {
				enums = append(enums, protoEnum{Name: enumName, Values: values})
			}
		}
	}
	return enums, nil
}

// protoEnumValueToName converts proto enum value name to a clean lowercase name.
// e.g. "ORDER_STATUS_PENDING" with enumName "OrderStatus" → "pending"
// e.g. "PENDING" → "pending"
func protoEnumValueToName(enumName, valueName string) string {
	// Build expected prefix from enum name: OrderStatus → ORDER_STATUS_
	prefix := toScreamingSnake(enumName) + "_"
	upper := strings.ToUpper(valueName)

	// Strip prefix if present
	if strings.HasPrefix(upper, prefix) {
		return strings.ToLower(upper[len(prefix):])
	}
	// Otherwise just lowercase the whole thing
	return strings.ToLower(valueName)
}

// buildEnumContent generates the Go source for an enum.
func buildEnumContent(name string, values []protoEnumValue) string {
	var b strings.Builder

	b.WriteString("// Code generated by zctl. DO NOT EDIT.\n\n")
	b.WriteString("package enums\n\n")
	b.WriteString("import \"fmt\"\n\n")
	b.WriteString(fmt.Sprintf("type %s int8\n\n", name))

	// Constants
	b.WriteString("const (\n")
	for _, v := range values {
		constName := name + toPascal(v.Name)
		b.WriteString(fmt.Sprintf("\t%s %s = %d\n", constName, name, v.Number))
	}
	b.WriteString(")\n\n")

	// Name map
	b.WriteString(fmt.Sprintf("var _%sNameMap = map[%s]string{\n", name, name))
	for _, v := range values {
		constName := name + toPascal(v.Name)
		b.WriteString(fmt.Sprintf("\t%s: %q,\n", constName, v.Name))
	}
	b.WriteString("}\n\n")

	// Value map
	b.WriteString(fmt.Sprintf("var _%sValueMap = map[string]%s{\n", name, name))
	for _, v := range values {
		constName := name + toPascal(v.Name)
		b.WriteString(fmt.Sprintf("\t%q: %s,\n", v.Name, constName))
	}
	b.WriteString("}\n\n")

	// String()
	b.WriteString(fmt.Sprintf("func (e %s) String() string {\n", name))
	b.WriteString(fmt.Sprintf("\tif name, ok := _%sNameMap[e]; ok {\n", name))
	b.WriteString("\t\treturn name\n")
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\treturn fmt.Sprintf(\"%s(%%d)\", int8(e))\n", name))
	b.WriteString("}\n\n")

	// IsValid()
	b.WriteString(fmt.Sprintf("func (e %s) IsValid() bool {\n", name))
	b.WriteString(fmt.Sprintf("\t_, ok := _%sNameMap[e]\n", name))
	b.WriteString("\treturn ok\n")
	b.WriteString("}\n\n")

	// Values()
	b.WriteString(fmt.Sprintf("func %sValues() []%s {\n", name, name))
	b.WriteString(fmt.Sprintf("\treturn []%s{\n", name))
	for _, v := range values {
		b.WriteString(fmt.Sprintf("\t\t%s,\n", name+toPascal(v.Name)))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Parse()
	b.WriteString(fmt.Sprintf("func Parse%s(s string) (%s, error) {\n", name, name))
	b.WriteString(fmt.Sprintf("\tif v, ok := _%sValueMap[s]; ok {\n", name))
	b.WriteString("\t\treturn v, nil\n")
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\treturn 0, fmt.Errorf(\"invalid %s: %%q\", s)\n", name))
	b.WriteString("}\n\n")

	// Int8()
	b.WriteString(fmt.Sprintf("func (e %s) Int8() int8 {\n", name))
	b.WriteString("\treturn int8(e)\n")
	b.WriteString("}\n")

	return b.String()
}

// ─── String helpers ──────────────────────────────────────────────────────────────

// toSnake converts CamelCase to snake_case, keeping consecutive uppercase
// letters (acronyms) together as one word.
//
//	OrderStatus  → order_status
//	CIDAppStatus → cid_app_status
//	HTTPSProxy   → https_proxy
//	GetCIDList   → get_cid_list
func toSnake(s string) string {
	runes := []rune(s)
	var result strings.Builder
	for i, r := range runes {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := runes[i-1]
			// Insert '_' when:
			// 1. Previous char is lowercase (camel boundary): "orderS" → "order_s"
			// 2. Previous char is uppercase BUT next char is lowercase (acronym end):
			//    "CIDA" at 'A' when next is 'p' → "CID_A" → "cid_app"
			if prev >= 'a' && prev <= 'z' {
				result.WriteByte('_')
			} else if i+1 < len(runes) && runes[i+1] >= 'a' && runes[i+1] <= 'z' {
				result.WriteByte('_')
			}
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

// toScreamingSnake: OrderStatus → ORDER_STATUS
func toScreamingSnake(s string) string {
	return strings.ToUpper(toSnake(s))
}

// toPascal: "pending" → "Pending", "paid_out" → "PaidOut"
func toPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
