package generator

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// MergeDescProtos scans descDir recursively for .proto files,
// merges all message/enum definitions and combines all service rpc methods
// into a single service block, writing the result to outputPath.
func MergeDescProtos(descDir, outputPath, serviceName string) error {
	var protoFiles []string
	err := filepath.Walk(descDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".proto") {
			protoFiles = append(protoFiles, path)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("failed to walk desc directory: %w", err)
	}

	// Sort: base.proto first, then alphabetically
	sort.Slice(protoFiles, func(i, j int) bool {
		iBase := filepath.Base(protoFiles[i]) == "base.proto"
		jBase := filepath.Base(protoFiles[j]) == "base.proto"
		if iBase != jBase {
			return iBase
		}
		return protoFiles[i] < protoFiles[j]
	})

	svcLower := strings.ToLower(serviceName)
	svcCamel := strings.ToUpper(serviceName[:1]) + serviceName[1:]

	var messageLines strings.Builder // all message/enum definitions
	var rpcLines strings.Builder     // all rpc method lines

	serviceRe := regexp.MustCompile(`^\s*service\s+\w+\s*\{`)
	rpcRe := regexp.MustCompile(`^\s*rpc\s+`)
	headerSkip := regexp.MustCompile(`^\s*(syntax|package|option\s+(go_package|java_package))`)

	for _, f := range protoFiles {
		relPath, _ := filepath.Rel(descDir, f)
		content, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", f, err)
		}

		messageLines.WriteString(fmt.Sprintf("// ---- from desc/%s ----\n\n", relPath))

		scanner := bufio.NewScanner(strings.NewReader(string(content)))
		inService := false
		braceDepth := 0

		for scanner.Scan() {
			line := scanner.Text()
			trimmed := strings.TrimSpace(line)

			// Skip proto header lines
			if headerSkip.MatchString(trimmed) {
				continue
			}

			// Detect service block start
			if serviceRe.MatchString(trimmed) {
				inService = true
				braceDepth = strings.Count(trimmed, "{") - strings.Count(trimmed, "}")
				// Add a comment to rpcLines for traceability
				rpcLines.WriteString(fmt.Sprintf("\n  // ---- from desc/%s ----\n", relPath))
				continue
			}

			if inService {
				braceDepth += strings.Count(trimmed, "{") - strings.Count(trimmed, "}")
				if braceDepth <= 0 {
					inService = false
					continue
				}
				// Collect rpc lines and comments inside service block
				if rpcRe.MatchString(trimmed) || strings.HasPrefix(trimmed, "//") || trimmed == "" {
					rpcLines.WriteString(line)
					rpcLines.WriteByte('\n')
				}
				continue
			}

			// Outside service block: message/enum definitions
			messageLines.WriteString(line)
			messageLines.WriteByte('\n')
		}
		messageLines.WriteByte('\n')
	}

	// Compose final merged proto
	var buf strings.Builder
	buf.WriteString("// ┌────────────────────────────────────────────────────────────────────────┐\n")
	buf.WriteString("// │         AUTO-GENERATED FILE — DO NOT EDIT                              │\n")
	buf.WriteString("// │                                                                        │\n")
	buf.WriteString("// │  This file is generated by: zctl rpc merge-proto                       │\n")
	buf.WriteString("// │  Source: desc/**/*.proto                                               │\n")
	buf.WriteString("// │  To modify, edit files under desc/ then run: make gen-rpc              │\n")
	buf.WriteString("// └────────────────────────────────────────────────────────────────────────┘\n\n")
	buf.WriteString(fmt.Sprintf("syntax = \"proto3\";\n\npackage %s;\noption go_package = \"./%s\";\n\n", svcLower, svcLower))
	buf.WriteString(messageLines.String())
	buf.WriteString(fmt.Sprintf("service %s {\n", svcCamel))
	buf.WriteString(rpcLines.String())
	buf.WriteString("}\n")

	// Write with read-only permission (0444) to discourage manual edits.
	// MergeDescProtos itself will chmod before writing if file exists.
	if _, err := os.Stat(outputPath); err == nil {
		os.Chmod(outputPath, 0644) // temporarily writable for overwrite
	}
	if err := os.WriteFile(outputPath, []byte(buf.String()), 0444); err != nil {
		return err
	}
	return nil
}
