package generator

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/qqz14/zctl/util/name"
)

// MergeDescProtos scans descDir recursively for .proto files,
// merges all message/enum definitions and combines all service rpc methods
// into a single service block, writing the result to outputPath.
func MergeDescProtos(descDir, outputPath, serviceName string) error {
	var protoFiles []string
	err := filepath.Walk(descDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".proto") {
			protoFiles = append(protoFiles, path)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("failed to walk desc directory: %w", err)
	}

	// Sort: base.proto first, then alphabetically
	sort.Slice(protoFiles, func(i, j int) bool {
		iBase := filepath.Base(protoFiles[i]) == "base.proto"
		jBase := filepath.Base(protoFiles[j]) == "base.proto"
		if iBase != jBase {
			return iBase
		}
		return protoFiles[i] < protoFiles[j]
	})

	// Service-name normalization (single source of truth):
	//   - protoPkg : proto3 package identifier (no dashes, lower)            "cs-agent-rpc" → "csagentrpc"
	//   - svcGo    : PascalCase Go-style service identifier                  "cs-agent-rpc" → "CsAgentRpc"
	// Both inputs `cs-agent-rpc` / `cs_agent_rpc` / `csAgentRpc` map to the same outputs.
	protoPkg := name.ProtoPkg(serviceName)
	svcGo := name.ServiceGoIdent(serviceName)

	var messageLines strings.Builder // all message/enum definitions
	var rpcLines strings.Builder     // all rpc method lines
	importSet := make(map[string]bool) // deduplicated import lines

	serviceRe := regexp.MustCompile(`^\s*service\s+\w+\s*\{`)
	rpcRe := regexp.MustCompile(`^\s*rpc\s+`)
	headerSkip := regexp.MustCompile(`^\s*(syntax|package|option\s+(go_package|java_package))`)
	importRe := regexp.MustCompile(`^\s*import\s+`)

	for _, f := range protoFiles {
		relPath, _ := filepath.Rel(descDir, f)
		relPath = filepath.ToSlash(relPath)
		content, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("failed to read %s: %w", f, err)
		}

		messageLines.WriteString(fmt.Sprintf("// ---- from desc/%s ----\n\n", relPath))

		scanner := bufio.NewScanner(strings.NewReader(string(content)))
		inService := false
		braceDepth := 0
		// rpcBraceDepth>0 表示当前正处在 rpc 花括号块体内，按花括号配平
		// 整段原样保留 rpc 行 + 内部 option 行（如 google.api.http）+ 收尾 `}`。
		// 仅在 rpc 块体外才依照 rpcRe / 注释 / 空行 等老规则决定是否保留。
		rpcBraceDepth := 0

		for scanner.Scan() {
			line := scanner.Text()
			trimmed := strings.TrimSpace(line)

			// Skip proto header lines
			if headerSkip.MatchString(trimmed) {
				continue
			}

			// Collect import lines (deduplicated)
			if importRe.MatchString(trimmed) {
				importSet[trimmed] = true
				continue
			}

			// Detect service block start
			if serviceRe.MatchString(trimmed) {
				inService = true
				braceDepth = strings.Count(trimmed, "{") - strings.Count(trimmed, "}")
				// Add a comment to rpcLines for traceability
				rpcLines.WriteString(fmt.Sprintf("\n  // ---- from desc/%s ----\n", relPath))
				continue
			}

			if inService {
				// 已经在某个 rpc 的花括号块体内 → 整行原样保留并继续配平
				if rpcBraceDepth > 0 {
					rpcLines.WriteString(line)
					rpcLines.WriteByte('\n')
					rpcBraceDepth += strings.Count(trimmed, "{") - strings.Count(trimmed, "}")
					if rpcBraceDepth <= 0 {
						rpcBraceDepth = 0
					}
					continue
				}

				braceDepth += strings.Count(trimmed, "{") - strings.Count(trimmed, "}")
				if braceDepth <= 0 {
					inService = false
					continue
				}
				// rpc 行：可能是单行（以 `;` 结尾）也可能是花括号块开头（以 `{` 结尾）
				if rpcRe.MatchString(trimmed) {
					rpcLines.WriteString(line)
					rpcLines.WriteByte('\n')
					// 进入 rpc 块体：行内净开 `{` 大于 0 → 设置 depth
					depth := strings.Count(trimmed, "{") - strings.Count(trimmed, "}")
					if depth > 0 {
						rpcBraceDepth = depth
					}
					continue
				}
				// 注释 / 空行：保留，作为 rpc 之间的间隔说明
				if strings.HasPrefix(trimmed, "//") || trimmed == "" {
					rpcLines.WriteString(line)
					rpcLines.WriteByte('\n')
				}
				continue
			}

			// Outside service block: message/enum definitions
			messageLines.WriteString(line)
			messageLines.WriteByte('\n')
		}
		messageLines.WriteByte('\n')
	}

	// Compose final merged proto
	var buf strings.Builder
	buf.WriteString("// ┌────────────────────────────────────────────────────────────────────────┐\n")
	buf.WriteString("// │         AUTO-GENERATED FILE — DO NOT EDIT                              │\n")
	buf.WriteString("// │                                                                        │\n")
	buf.WriteString("// │  This file is generated by: zctl rpc merge-proto                       │\n")
	buf.WriteString("// │  Source: desc/**/*.proto                                               │\n")
	buf.WriteString("// │  To modify, edit files under desc/ then run: make gen-rpc              │\n")
	buf.WriteString("// └────────────────────────────────────────────────────────────────────────┘\n\n")
	buf.WriteString(fmt.Sprintf("syntax = \"proto3\";\n\npackage %s;\noption go_package = \"./%s\";\n\n", protoPkg, protoPkg))

	// Write deduplicated imports
	if len(importSet) > 0 {
		// Sort for deterministic output
		importLines := make([]string, 0, len(importSet))
		for imp := range importSet {
			importLines = append(importLines, imp)
		}
		sort.Strings(importLines)
		for _, imp := range importLines {
			buf.WriteString(imp)
			buf.WriteByte('\n')
		}
		buf.WriteByte('\n')
	}

	buf.WriteString(messageLines.String())
	buf.WriteString(fmt.Sprintf("service %s {\n", svcGo))
	buf.WriteString(rpcLines.String())
	buf.WriteString("}\n")

	// Write with read-only permission (0444) to discourage manual edits.
	// MergeDescProtos itself will chmod before writing if file exists.
	if _, err := os.Stat(outputPath); err == nil {
		os.Chmod(outputPath, 0644) // temporarily writable for overwrite
	}
	if err := os.WriteFile(outputPath, []byte(buf.String()), 0444); err != nil {
		return err
	}
	return nil
}
