package checker

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// RunLint runs golangci-lint with perf/resource-leak focused config.
// Supports both golangci-lint v1 (--out-format) and v2 (--output.XXX.path).
// Writes lint.json, lint.html and lint.txt to outDir.
// Level: FAIL if error-level issues > 0; WARN if only warnings.
func RunLint(dir, outDir string) *Result {
	if _, err := exec.LookPath("golangci-lint"); err != nil {
		return Skip("golangci-lint not installed (run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest)")
	}

	// Ensure .golangci.yml exists in the project; generate a default if not.
	ensureGolangciYml(dir)

	v2 := isGolangciLintV2()
	jsonOut := filepath.Join(outDir, "lint.json")
	htmlOut := filepath.Join(outDir, "lint.html")
	txtOut := filepath.Join(outDir, "lint.txt")

	// Single run with all three output formats simultaneously (v2 supports this).
	// Fall back to three separate runs for v1.
	if v2 {
		runLintV2(dir, jsonOut, htmlOut, txtOut)
	} else {
		runLintV1Format(dir, "json", jsonOut)
		runLintV1Format(dir, "html", htmlOut)
		runLintV1Format(dir, "colored-line-number", txtOut)
	}

	issues := parseLintJSON(jsonOut)
	if len(issues) == 0 {
		return Pass("no lint issues found")
	}

	var errors, warnings []string
	for _, iss := range issues {
		entry := fmt.Sprintf("%s:%d:%d: [%s] %s",
			iss.Pos.Filename, iss.Pos.Line, iss.Pos.Column, iss.FromLinter, iss.Text)
		if iss.Severity == "error" {
			errors = append(errors, entry)
		} else {
			warnings = append(warnings, entry)
		}
	}

	if len(errors) > 0 {
		all := append(errors, warnings...)
		return Fail(
			fmt.Sprintf("%d error(s), %d warning(s) — see build/perf/lint.html", len(errors), len(warnings)),
			all,
		)
	}
	return Warn(
		fmt.Sprintf("%d warning(s) — see build/perf/lint.html", len(warnings)),
		warnings,
	)
}

// isGolangciLintV2 detects whether the installed golangci-lint is v2+.
// v2 changed the output flag from --out-format to --output.XXX.path.
func isGolangciLintV2() bool {
	out, err := exec.Command("golangci-lint", "--version").Output()
	if err != nil {
		return false
	}
	// Version string: "golangci-lint has version 2.x.y ..."
	return strings.Contains(string(out), " version 2.") ||
		strings.Contains(string(out), "v2.")
}

// runLintV2 runs a single golangci-lint v2 invocation writing all three formats.
func runLintV2(dir, jsonOut, htmlOut, txtOut string) {
	args := []string{
		"run", "--timeout=90s",
		"--output.json.path=" + jsonOut,
		"--output.html.path=" + htmlOut,
		"--output.text.path=" + txtOut,
		"./...",
	}
	cmd := exec.Command("golangci-lint", args...)
	cmd.Dir = dir
	_ = cmd.Run()
}

// runLintV1Format runs golangci-lint v1 with a single output format.
func runLintV1Format(dir, format, outFile string) {
	args := []string{"run", "--timeout=90s", "--out-format=" + format, "./..."}
	cmd := exec.Command("golangci-lint", args...)
	cmd.Dir = dir
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	_ = cmd.Run()
	_ = os.WriteFile(outFile, out.Bytes(), 0o644)
}

// lintIssue mirrors the JSON structure of golangci-lint output.
type lintIssue struct {
	Text       string `json:"Text"`
	FromLinter string `json:"FromLinter"`
	Severity   string `json:"Severity"`
	Pos        struct {
		Filename string `json:"Filename"`
		Line     int    `json:"Line"`
		Column   int    `json:"Column"`
	} `json:"Pos"`
}

type lintReport struct {
	Issues []lintIssue `json:"Issues"`
}

func parseLintJSON(jsonPath string) []lintIssue {
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return nil
	}
	var rep lintReport
	if err := json.Unmarshal(data, &rep); err != nil {
		return nil
	}
	return rep.Issues
}

// ensureGolangciYml writes a default .golangci.yml if the project does not have one.
// Focused on: resource leaks, performance patterns, code style (放宽版).
func ensureGolangciYml(dir string) {
	ymlPath := filepath.Join(dir, ".golangci.yml")
	if fileExists(ymlPath) {
		return
	}
	_ = os.WriteFile(ymlPath, []byte(defaultGolangciYml), 0o644)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// defaultGolangciYml is the auto-generated .golangci.yml template (golangci-lint v2 format).
// Focused on resource leaks and performance; rules are intentionally
// lenient (warn-only) to avoid overwhelming teams on first run.
const defaultGolangciYml = `# .golangci.yml — auto-generated by zctl perf scan
# golangci-lint v2 format (https://golangci-lint.run/docs/upgrading/v2/)
# Focus: resource leaks, performance patterns, code style (放宽版)

version: "2"

run:
  timeout: 90s

formatters:
  enable:
    - gofmt          # 格式化检查（v2 中 formatter 与 linter 分离）

linters:
  default: none
  enable:
    # ── 内置检查 ──
    - govet          # 锁拷贝 / printf格式 / 不可达代码

    # ── 资源泄漏 ──
    - bodyclose      # HTTP response.Body 未关闭 → 连接池耗尽
    - sqlclosecheck  # sql.Rows / sql.Stmt 未关闭 → DB连接池耗尽
    - rowserrcheck   # rows.Err() 未检查 → 静默丢失DB遍历错误
    - noctx          # http.NewRequest 未传 context → 请求无法取消

    # ── 性能模式 ──
    - gocritic       # hugeParam(大结构体值传递) + performance tag
    - prealloc       # 循环内反复 append → slice 多次扩容
    - fatcontext     # 循环内 context.WithValue → 嵌套context内存压力

    # ── goroutine/context 泄漏风险 ──
    - contextcheck   # context 未正确传递 → goroutine 无法取消

    # ── 代码规范 ──
    - staticcheck    # 低效代码模式

  settings:
    gocritic:
      enabled-tags:
        - performance
        - diagnostic
      disabled-checks:
        - appendAssign
    staticcheck:
      checks: ["all", "-SA1019", "-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022"]
    rowserrcheck:
      packages:
        - database/sql
        - github.com/jmoiron/sqlx
    prealloc:
      simple: true
      range-loops: true
      for-loops: false

issues:
  exclude-dirs:
    - ent
    - types
    - migrations
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - bodyclose
        - contextcheck
        - noctx
    - path: "mock/"
      linters:
        - govet
        - gocritic
  max-issues-per-linter: 50
  max-same-issues: 10
`

// EnsureGolangciYmlInProject is exported for use by genscaffold.
func EnsureGolangciYmlInProject(dir string) {
	ensureGolangciYml(dir)
}

// GolangciYmlContent returns the default .golangci.yml content for embedding in templates.
func GolangciYmlContent() string {
	// Remove the auto-generate comment for scaffold use
	return strings.Replace(defaultGolangciYml,
		"# .golangci.yml — auto-generated by zctl perf scan\n",
		"# .golangci.yml — generated by zctl rpc new\n", 1)
}
