package checker

// redis_capture.go — Generic Redis command capture probe generator.
//
// Business code change (permanent, 2 lines, zero prod overhead):
//   internal/svc/zctl_hooks.go   → generated once by InjectRedisHookFile()
//   service_context.go line      → goredis.MustNewRedis(..., _zctlRedisHooks...)
//
// Everything else is generated by zctl and auto-deleted after scan.
//
// Generic strategy: zctl AST-scans ServiceContext struct to discover fields,
// then generates fakeSvc init code that:
//   - *ent.Client fields       → nop ent driver
//   - *redis.Redis fields      → captureHook
//   - XxxDao interface fields  → impl.NewXxxDao(entClient) via implIdx constructors
//   - Other fields             → zero value (probe uses recover())

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/token"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// CapturedRedis maps "LogicType.LogicMethod" → deduplicated Redis command strings.
type CapturedRedis map[string][]string

// RunRedisCapture generates and runs a Redis capture probe in the target project.
// Returns nil, nil if the project has no injection point or no Logic methods.
func RunRedisCapture(dir string) (CapturedRedis, error) {
	moduleName := detectModuleName(dir)
	if moduleName == "" {
		return nil, nil
	}
	if !hasRedisInjectionPoint(dir) {
		return nil, fmt.Errorf("no injection point: run 'zctl perf inject %s' first", dir)
	}

	logics := scanAllLogics(dir, moduleName)
	if len(logics) == 0 {
		return nil, nil
	}

	// Scan ServiceContext to generate generic fakeSvc init code
	svcFields := scanServiceContextFields(dir, moduleName)
	ctors := scanDAOConstructors(dir) // recvType → "impl.NewXxxDao"

	probeDir := filepath.Join(dir, "_zctl_redis_probe")
	if err := os.MkdirAll(probeDir, 0o755); err != nil {
		return nil, fmt.Errorf("mkdir: %w", err)
	}
	defer os.RemoveAll(probeDir)

	code, err := generateRedisProbe(moduleName, logics, svcFields, ctors, dir)
	if err != nil {
		return nil, fmt.Errorf("generate: %w", err)
	}
	if err := os.WriteFile(filepath.Join(probeDir, "main.go"), []byte(code), 0o644); err != nil {
		return nil, fmt.Errorf("write: %w", err)
	}

	cmd := exec.Command("go", "run", "./_zctl_redis_probe/main.go")
	cmd.Dir = dir
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("probe: %w\n%s", err, stderr.String())
	}
	return parseRedisCaptureOutput(stdout.String()), nil
}

func parseRedisCaptureOutput(output string) CapturedRedis {
	result := make(CapturedRedis)
	scanner := bufio.NewScanner(strings.NewReader(output))
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, "\t", 3)
		if len(parts) != 3 {
			continue
		}
		key := parts[0] + "." + parts[1]
		cmd := parts[2]
		for _, existing := range result[key] {
			if existing == cmd {
				goto next
			}
		}
		result[key] = append(result[key], cmd)
	next:
	}
	return result
}

// ── Injection point ───────────────────────────────────────────────────────────

func hasRedisInjectionPoint(dir string) bool {
	data, err := os.ReadFile(filepath.Join(dir, "internal", "svc", "zctl_hooks.go"))
	if err != nil {
		return false
	}
	return strings.Contains(string(data), "ZctlInjectRedisHook")
}

// InjectRedisHookFile generates internal/svc/zctl_hooks.go in the target project.
// Idempotent. Call once per project; the 2-line change to service_context.go is manual.
func InjectRedisHookFile(dir, moduleName string) error {
	hooksFile := filepath.Join(dir, "internal", "svc", "zctl_hooks.go")
	if data, err := os.ReadFile(hooksFile); err == nil {
		if strings.Contains(string(data), "ZctlInjectRedisHook") {
			return nil
		}
	}
	content := fmt.Sprintf("package svc\n\nimport goredis %q\n\n"+
		"// _zctlRedisHooks is the zctl perf injection point. Default nil — zero prod overhead.\n"+
		"var _zctlRedisHooks []goredis.Option\n\n"+
		"// ZctlInjectRedisHook sets a Redis hook for zctl probe only.\n"+
		"func ZctlInjectRedisHook(hook goredis.Option) {\n\t_zctlRedisHooks = append(_zctlRedisHooks, hook)\n}\n",
		"github.com/zeromicro/go-zero/core/stores/redis")
	return os.WriteFile(hooksFile, []byte(content), 0o644)
}

// ── ServiceContext field scanning (generic) ───────────────────────────────────

// svcField describes one field in the ServiceContext struct.
type svcField struct {
	Name     string // e.g. "IamAPIDao", "DB", "Redis"
	TypeName string // e.g. "IamAPIDao", "Client", "Redis"
	TypePkg  string // short pkg name e.g. "dao", "ent", "redis" (from selector)
	Kind     string // "entclient" | "redis" | "dao" | "other"
}

// scanServiceContextFields reads internal/svc/service_context.go and returns
// the fields of ServiceContext, classified by kind.
func scanServiceContextFields(dir, moduleName string) []svcField {
	fset := token.NewFileSet()
	svcDir := filepath.Join(dir, "internal", "svc")
	var result []svcField

	entries, _ := os.ReadDir(svcDir)
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(svcDir, e.Name())
		src, _ := os.ReadFile(path)
		f, err := parseWithGoParser(fset, path, src)
		if err != nil {
			continue
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != "ServiceContext" {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				for _, field := range st.Fields.List {
					if len(field.Names) == 0 {
						continue
					}
					for _, name := range field.Names {
						sf := svcField{Name: name.Name}
						sf.TypeName, sf.TypePkg = extractFieldType(field.Type)
						sf.Kind = classifyFieldKind(sf.TypeName, sf.TypePkg)
						result = append(result, sf)
					}
				}
			}
		}
	}
	return result
}

// extractFieldType returns (typeName, pkgName) from a field type expression.
// *ent.Client → ("Client", "ent")
// *redis.Redis → ("Redis", "redis" or "goredis")
// dao.IamAPIDao → ("IamAPIDao", "dao")
// *entx.Tx → ("Tx", "entx")
func extractFieldType(expr ast.Expr) (typeName, pkgName string) {
	switch v := expr.(type) {
	case *ast.StarExpr:
		return extractFieldType(v.X)
	case *ast.SelectorExpr:
		if id, ok := v.X.(*ast.Ident); ok {
			return v.Sel.Name, id.Name
		}
	case *ast.Ident:
		return v.Name, ""
	}
	return "", ""
}

// classifyFieldKind classifies a ServiceContext field.
func classifyFieldKind(typeName, pkgName string) string {
	lower := strings.ToLower(typeName)
	lowerPkg := strings.ToLower(pkgName)

	if typeName == "Client" && (lowerPkg == "ent" || lowerPkg == "entgen") {
		return "entclient"
	}
	if typeName == "Redis" && strings.Contains(lowerPkg, "redis") {
		return "redis"
	}
	if strings.HasSuffix(lower, "dao") {
		return "dao"
	}
	// Tx wrappers and other ent-related types
	if typeName == "Tx" || strings.Contains(lower, "tx") {
		return "other" // skip — nil is fine
	}
	return "other"
}

// ── Logic scanning ────────────────────────────────────────────────────────────

type logicInfo struct {
	PkgImport   string
	PkgAlias    string
	CtorName    string
	MethodName  string
	ReqType     string
}

func scanAllLogics(dir, moduleName string) []logicInfo {
	fset := token.NewFileSet()
	logicDir := filepath.Join(dir, "internal", "logic")
	if _, err := os.Stat(logicDir); err != nil {
		return nil
	}

	var out []logicInfo
	seenKey := map[string]bool{}
	pkgAliasMap := map[string]string{} // pkgImport → alias
	pkgAliasCount := map[string]int{}  // base alias → count for dedup

	_ = filepath.WalkDir(logicDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		src, _ := os.ReadFile(path)
		f, err := parseWithGoParser(fset, path, src)
		if err != nil {
			return nil
		}
		pkgName := f.Name.Name
		relDir := filepath.ToSlash(strings.TrimPrefix(filepath.Dir(path), dir+string(os.PathSeparator)))
		pkgImport := moduleName + "/" + relDir

		// Build unique alias for this package
		if _, ok := pkgAliasMap[pkgImport]; !ok {
			base := pkgName
			alias := base
			if pkgAliasCount[base] > 0 {
				alias = fmt.Sprintf("%s%d", base, pkgAliasCount[base]+1)
			}
			pkgAliasCount[base]++
			pkgAliasMap[pkgImport] = alias
		}
		alias := pkgAliasMap[pkgImport]

		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv == nil || !isExported(fd.Name.Name) || fd.Body == nil {
				continue
			}
			recv := receiverTypeName(fd.Recv.List[0].Type)
			if !strings.HasSuffix(recv, "Logic") {
				continue
			}
			ctorName := "New" + recv
			methodName := fd.Name.Name
			key := pkgImport + "::" + ctorName + "::" + methodName
			if seenKey[key] {
				continue
			}

			// Extract req type from first pointer param (skip context)
			reqType := extractFirstReqType(fd.Type.Params)

			seenKey[key] = true
			out = append(out, logicInfo{
				PkgImport:  pkgImport,
				PkgAlias:   alias,
				CtorName:   ctorName,
				MethodName: methodName,
				ReqType:    reqType,
			})
		}
		return nil
	})

	sort.Slice(out, func(i, j int) bool {
		return out[i].CtorName+out[i].MethodName < out[j].CtorName+out[j].MethodName
	})
	return out
}

// extractFirstReqType finds the first *pkg.Type parameter (skipping context.Context).
// Returns "TypeName" only (pkg prefix resolved at template time via pbtypes alias).
func extractFirstReqType(params *ast.FieldList) string {
	if params == nil {
		return "Empty"
	}
	for _, param := range params.List {
		star, ok := param.Type.(*ast.StarExpr)
		if !ok {
			continue
		}
		switch x := star.X.(type) {
		case *ast.SelectorExpr:
			return x.Sel.Name // e.g. "PassportTokenReq"
		case *ast.Ident:
			if x.Name != "Context" {
				return x.Name
			}
		}
	}
	return "Empty"
}

// scanDAOConstructors returns map: recvType (concrete struct) → "impl.NewXxxDao"
// by AST-tracing the return statement of New* funcs in internal/dao/impl/.
func scanDAOConstructors(dir string) map[string]string {
	fset := token.NewFileSet()
	result := map[string]string{}
	implDir := filepath.Join(dir, "internal", "dao", "impl")
	if _, err := os.Stat(implDir); err != nil {
		return result
	}
	entries, _ := os.ReadDir(implDir)
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		path := filepath.Join(implDir, e.Name())
		src, _ := os.ReadFile(path)
		f, err := parseWithGoParser(fset, path, src)
		if err != nil {
			continue
		}
		// Collect struct names in this file
		structNames := map[string]bool{}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := ts.Type.(*ast.StructType); ok {
					structNames[ts.Name.Name] = true
				}
			}
		}
		// For each New* func, find which struct it returns
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv != nil || !strings.HasPrefix(fd.Name.Name, "New") || fd.Body == nil {
				continue
			}
			var foundStruct string
			ast.Inspect(fd.Body, func(n ast.Node) bool {
				if foundStruct != "" {
					return false
				}
				ul, ok := n.(*ast.UnaryExpr)
				if !ok || ul.Op.String() != "&" {
					return true
				}
				cl, ok := ul.X.(*ast.CompositeLit)
				if !ok {
					return true
				}
				ident, ok := cl.Type.(*ast.Ident)
				if !ok {
					return true
				}
				if structNames[ident.Name] {
					foundStruct = ident.Name
				}
				return true
			})
			if foundStruct != "" {
				result[foundStruct] = "impl." + fd.Name.Name
			}
		}
	}
	return result
}

func detectTypesPkg(dir, moduleName string) string {
	typesDir := filepath.Join(dir, "types")
	if _, err := os.Stat(typesDir); err != nil {
		return moduleName + "/types"
	}
	entries, _ := os.ReadDir(typesDir)
	for _, e := range entries {
		if e.IsDir() {
			return moduleName + "/types/" + e.Name()
		}
	}
	return moduleName + "/types"
}

func detectGoRedisV9Pkg(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return "github.com/redis/go-redis/v9"
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.Contains(line, "go-redis/v9") {
			parts := strings.Fields(line)
			if len(parts) > 0 {
				return parts[0]
			}
		}
	}
	return "github.com/redis/go-redis/v9"
}

// ── Probe code generation ─────────────────────────────────────────────────────

type redisProbeData struct {
	RedisPkg   string
	RedisV9Pkg string
	SvcPkg     string
	EntPkg     string
	TypesPkg   string
	ImplPkg    string
	Imports    string // logic package imports
	FakeSvc    string // generated fakeSvc field initializations
	Calls      string // Logic method call code
}

const redisProbeTemplate = `// Code generated by zctl perf — DO NOT EDIT. Auto-deleted after scan.
package main

import (
	"context"
	"fmt"
	"strings"
	"sync"

	"entgo.io/ent/dialect"
	goredis "{{.RedisPkg}}"
	redisv9 "{{.RedisV9Pkg}}"
	"{{.SvcPkg}}"
	"{{.EntPkg}}"
	"{{.ImplPkg}}"
	pbtypes "{{.TypesPkg}}"
{{.Imports}}
)

// ── nop ent driver ────────────────────────────────────────────────────────────

type nopDrv struct{}
func (nopDrv) Exec(_ context.Context, _ string, _, _ interface{}) error  { return nil }
func (nopDrv) Query(_ context.Context, _ string, _, _ interface{}) error { return nil }
func (nopDrv) Tx(_ context.Context) (dialect.Tx, error)                  { return nopTx{}, nil }
func (nopDrv) Close() error                                               { return nil }
func (nopDrv) Dialect() string                                            { return dialect.MySQL }
type nopTx struct{}
func (nopTx) Exec(_ context.Context, _ string, _, _ interface{}) error  { return nil }
func (nopTx) Query(_ context.Context, _ string, _, _ interface{}) error { return nil }
func (nopTx) Commit() error                                              { return nil }
func (nopTx) Rollback() error                                            { return nil }

// ── Redis capture hook ────────────────────────────────────────────────────────

var (
	rmu    sync.Mutex
	rLog   []string
	rLabel string
)

type captureHook struct{}
func (captureHook) DialHook(next redisv9.DialHook) redisv9.DialHook { return next }
func (captureHook) ProcessHook(next redisv9.ProcessHook) redisv9.ProcessHook {
	return func(ctx context.Context, cmd redisv9.Cmder) error {
		s := cmd.String()
		if idx := strings.LastIndex(s, ": "); idx > 0 { s = s[:idx] }
		if s = strings.TrimSpace(s); s != "" {
			rmu.Lock(); rLog = append(rLog, rLabel+"\t"+s); rmu.Unlock()
		}
		return next(ctx, cmd)
	}
}
func (captureHook) ProcessPipelineHook(next redisv9.ProcessPipelineHook) redisv9.ProcessPipelineHook {
	return func(ctx context.Context, cmds []redisv9.Cmder) error {
		for _, cmd := range cmds {
			s := cmd.String()
			if idx := strings.LastIndex(s, ": "); idx > 0 { s = s[:idx] }
			if s = strings.TrimSpace(s); s != "" {
				rmu.Lock(); rLog = append(rLog, rLabel+"\t"+s); rmu.Unlock()
			}
		}
		return next(ctx, cmds)
	}
}

func main() {
	ctx := context.Background()

	// Inject capture hook via project injection point
	svc.ZctlInjectRedisHook(goredis.WithHook(captureHook{}))

	// Build shared resources
	entClient := ent.NewClient(ent.Driver(nopDrv{}))
	defer entClient.Close()
	rds := goredis.MustNewRedis(goredis.RedisConf{Host: "127.0.0.1:6379", Type: "node"},
		goredis.WithHook(captureHook{}))

	// Build fake ServiceContext — generated from AST scan of ServiceContext struct
	fakeSvc := &svc.ServiceContext{
{{.FakeSvc}}
	}
	_ = fakeSvc

	// Call each Logic method with zero-value req; recover from panics
{{.Calls}}

	for _, line := range rLog { fmt.Println(line) }
}
`

func generateRedisProbe(moduleName string, logics []logicInfo, svcFields []svcField, ctors map[string]string, dir string) (string, error) {
	// ── Logic imports ──
	importSet := map[string]string{}
	for _, l := range logics {
		importSet[l.PkgImport] = l.PkgAlias
	}
	var importLines []string
	for pkg, alias := range importSet {
		if alias == filepath.Base(pkg) {
			importLines = append(importLines, fmt.Sprintf("\t%q", pkg))
		} else {
			importLines = append(importLines, fmt.Sprintf("\t%s %q", alias, pkg))
		}
	}
	sort.Strings(importLines)

	// ── fakeSvc field initializations (generic, from AST scan) ──
	var svcLines []string
	for _, sf := range svcFields {
		switch sf.Kind {
		case "entclient":
			svcLines = append(svcLines, fmt.Sprintf("\t\t%s: entClient,", sf.Name))
		case "redis":
			svcLines = append(svcLines, fmt.Sprintf("\t\t%s: rds,", sf.Name))
		case "dao":
			// Find constructor: ctors maps recvType (e.g. "iamapiOceanBaseDao") → "impl.NewIamAPIOceanBaseDao"
			// ServiceContext field name is like "IamAPIDao" — match by lowercasing and stripping "Dao"
			ctor := findDaoCtor(sf.Name, ctors)
			if ctor != "" {
				svcLines = append(svcLines, fmt.Sprintf("\t\t%s: %s(entClient),", sf.Name, ctor))
			}
			// If no ctor found, leave as zero value (nil interface — probe recovers)
		}
		// "other" fields: omit (zero value = nil)
	}

	// ── Logic calls ──
	seen := map[string]bool{}
	var callLines []string
	for _, l := range logics {
		key := l.CtorName + "." + l.MethodName
		if seen[key] {
			continue
		}
		seen[key] = true
		typeName := strings.TrimPrefix(l.CtorName, "New")
		alias := importSet[l.PkgImport]
		callLines = append(callLines,
			fmt.Sprintf("\trLabel = %q", typeName+"\t"+l.MethodName),
			"\tfunc() {",
			"\t\tdefer func() { recover() }()",
			fmt.Sprintf("\t\t%s.%s(ctx, fakeSvc).%s(&pbtypes.%s{})", alias, l.CtorName, l.MethodName, l.ReqType),
			"\t}()",
		)
	}

	data := redisProbeData{
		RedisPkg:   "github.com/zeromicro/go-zero/core/stores/redis",
		RedisV9Pkg: detectGoRedisV9Pkg(dir),
		SvcPkg:     moduleName + "/internal/svc",
		EntPkg:     moduleName + "/ent",
		TypesPkg:   detectTypesPkg(dir, moduleName),
		ImplPkg:    moduleName + "/internal/dao/impl",
		Imports:    strings.Join(importLines, "\n"),
		FakeSvc:    strings.Join(svcLines, "\n"),
		Calls:      strings.Join(callLines, "\n"),
	}

	t, err := template.New("redis-probe").Parse(redisProbeTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// findDaoCtor maps a ServiceContext DAO field name to its constructor.
// "IamAPIDao" → looks in ctors for a key whose recvType lowercased matches
// the field name lowercased with "dao" stripped.
// e.g. "IamAPIDao" → lower "iamapiDao" → strip "dao" → "iamapi"
//      ctors["iamapiOceanBaseDao"] = "impl.NewIamAPIOceanBaseDao" → match "iamapi" prefix
func findDaoCtor(fieldName string, ctors map[string]string) string {
	// Strip "Dao" suffix from field name, lowercase
	target := strings.ToLower(strings.TrimSuffix(strings.TrimSuffix(fieldName, "Dao"), "dao"))
	if target == "" {
		return ""
	}
	// Find a ctor key that starts with target (after stripping impl suffix)
	for recvType, ctor := range ctors {
		lower := strings.ToLower(recvType)
		// recvType is like "iamapiOceanBaseDao" — strip known suffixes
		stripped := lower
		for _, sfx := range []string{"oceanbasedao", "mysqldao", "postgresdao", "sqlitedao", "dao"} {
			stripped = strings.TrimSuffix(stripped, sfx)
		}
		if stripped == target {
			return ctor
		}
	}
	return ""
}
